 -- MySQL Script generated by MySQL Workbench
-- 10/11/17 14:32:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amizade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amizade` (
  `Usuario_id` INT NOT NULL,
  `Usuario_id1` INT NOT NULL,
  INDEX `fk_Usuario_has_Usuario_Usuario1_idx` (`Usuario_id1` ASC),
  INDEX `fk_Usuario_has_Usuario_Usuario_idx` (`Usuario_id` ASC),
  PRIMARY KEY (`Usuario_id`, `Usuario_id1`),
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_id1`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conversas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conversas` (
  `Usuario_has_Usuario_Usuario_id` INT NOT NULL,
  `Usuario_has_Usuario_Usuario_id1` INT NOT NULL,
  `dia` DATE NULL,
  `texto` VARCHAR(250) NULL,
  INDEX `fk_mensagem_has_Usuario_has_Usuario_Usuario_has_Usuario1_idx` (`Usuario_has_Usuario_Usuario_id` ASC, `Usuario_has_Usuario_Usuario_id1` ASC),
  PRIMARY KEY (`Usuario_has_Usuario_Usuario_id`, `Usuario_has_Usuario_Usuario_id1`),
  CONSTRAINT `fk_mensagem_has_Usuario_has_Usuario_Usuario_has_Usuario1`
    FOREIGN KEY (`Usuario_has_Usuario_Usuario_id` , `Usuario_has_Usuario_Usuario_id1`)
    REFERENCES `mydb`.`amizade` (`Usuario_id` , `Usuario_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
