insert into mydb.usuario (id, nome, email, status) values (1, 'Abrahan', 'aloftin0@bigcartel.com','Olá pessoas da internet!');
insert into mydb.usuario (id, nome, email, status) values (2, 'Nathalie', 'ndoyley1@ucoz.ru','Olá Galera');
insert into mydb.usuario (id, nome, email, status) values (3, 'Tremayne', 'tmacura2@freewebs.com','Este chat é muito top');
insert into mydb.usuario (id, nome, email, status) values (4, 'Humfrid', 'hlockyer3@slideshare.net','O comunismo mata muita gente');
insert into mydb.usuario (id, nome, email, status) values (5, 'Gare', 'gwinspurr4@altervista.org','ÃO ÃO ÃO pelo fim do machismo');
insert into mydb.usuario (id, nome, email, status) values (6, 'Lucilia', 'ltolman5@webnode.com','Melhor que whats');
insert into mydb.usuario (id, nome, email) values (7, 'Debor', 'dbhar6@arstechnica.com');
insert into mydb.usuario (id, nome, email) values (8, 'Ashley', 'awoodcock7@1688.com');
insert into mydb.usuario (id, nome, email) values (9, 'Ermanno', 'eknappe8@goodreads.com');
insert into mydb.usuario (id, nome, email) values (10, 'Glennie', 'gshaylor9@squarespace.com');
insert into mydb.usuario (id, nome, email) values (11, 'Hamish', 'hklimshuka@ted.com');
insert into mydb.usuario (id, nome, email) values (12, 'Cherie', 'cjoulb@freewebs.com');
insert into mydb.usuario (id, nome, email) values (13, 'Janenna', 'jjaquesc@phoca.cz');
insert into mydb.usuario (id, nome, email) values (14, 'Pam', 'pmaccurlyed@tumblr.com');
insert into mydb.usuario (id, nome, email) values (15, 'Rhoda', 'rrockhille@privacy.gov.au');
insert into mydb.usuario (id, nome, email) values (16, 'Paton', 'ppidgeonf@netscape.com');
insert into mydb.usuario (id, nome, email) values (17, 'Letisha', 'lmcgilbeng@stumbleupon.com');
insert into mydb.usuario (id, nome, email) values (18, 'Starr', 'scoddringtonh@webnode.com');
insert into mydb.usuario (id, nome, email) values (19, 'Harlene', 'hwoodvinei@behance.net');
insert into mydb.usuario (id, nome, email) values (20, 'Noell', 'nwimpressj@buzzfeed.com');
insert into mydb.usuario (id, nome, email) values (21, 'Carolann', 'crichink@noaa.gov');
insert into mydb.usuario (id, nome, email) values (22, 'Jayson', 'jcornickl@npr.org');
insert into mydb.usuario (id, nome, email) values (23, 'Mei', 'mpedicanm@php.net');
insert into mydb.usuario (id, nome, email) values (24, 'Putnem', 'pwaddinghamn@virginia.edu');
insert into mydb.usuario (id, nome, email) values (25, 'Michal', 'meakleo@nature.com');
insert into mydb.usuario (id, nome, email) values (26, 'Davide', 'dguillouxp@twitpic.com');
insert into mydb.usuario (id, nome, email) values (27, 'Agnella', 'alettsq@abc.net.au');
insert into mydb.usuario (id, nome, email) values (28, 'Maighdiln', 'mwestgarthr@disqus.com');
insert into mydb.usuario (id, nome, email) values (29, 'Julieta', 'jgeddiss@epa.gov');
insert into mydb.usuario (id, nome, email) values (30, 'Brodie', 'btrunchiont@bandcamp.com');
insert into mydb.usuario (id, nome, email) values (31, 'Dall', 'doleaghamu@1688.com');
insert into mydb.usuario (id, nome, email) values (32, 'Jan', 'jmettrickv@blogger.com');
insert into mydb.usuario (id, nome, email) values (33, 'Corly', 'ccalbreathw@deliciousdays.com');
insert into mydb.usuario (id, nome, email) values (34, 'Amandi', 'amccormickx@storify.com');
insert into mydb.usuario (id, nome, email) values (35, 'Gualterio', 'gcrusy@paypal.com');
insert into mydb.usuario (id, nome, email) values (36, 'Hurley', 'hdoohanz@cnn.com');
insert into mydb.usuario (id, nome, email) values (37, 'Arny', 'ahamlet10@ca.gov');
insert into mydb.usuario (id, nome, email) values (38, 'Diane-marie', 'dklassmann11@blinklist.com');
insert into mydb.usuario (id, nome, email) values (39, 'Dannie', 'dconner12@networkadvertising.org');
insert into mydb.usuario (id, nome, email) values (40, 'Basilius', 'bmanion13@zimbio.com');
insert into mydb.usuario (id, nome, email) values (41, 'Woodrow', 'wdadd14@google.com.au');
insert into mydb.usuario (id, nome, email) values (42, 'Ara', 'ahillum15@webnode.com');
insert into mydb.usuario (id, nome, email) values (43, 'Lorry', 'lhardbattle16@usnews.com');
insert into mydb.usuario (id, nome, email) values (44, 'Harrie', 'hbeechcraft17@apple.com');
insert into mydb.usuario (id, nome, email) values (45, 'Matelda', 'mirnis18@abc.net.au');
insert into mydb.usuario (id, nome, email) values (46, 'Zonda', 'zhavelin19@businesswire.com');
insert into mydb.usuario (id, nome, email) values (47, 'Kale', 'kserris1a@ning.com');
insert into mydb.usuario (id, nome, email) values (48, 'Nicolette', 'nwestberg1b@wiley.com');
insert into mydb.usuario (id, nome, email) values (49, 'Clarice', 'ccarling1c@netlog.com');
insert into mydb.usuario (id, nome, email) values (50, 'Karlee', 'kbertomieu1d@printfriendly.com');

INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (1, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (1, 3);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (1, 4);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (1, 5);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 1);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 4);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 6);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 5);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 7);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (2, 5);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 4);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 9);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 8);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 25);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 24);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 22);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 20);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (3, 23);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 13);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 14);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 16);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 17);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 21);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (4, 22);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (5, 15);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (5, 18);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (5, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (5, 41);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (5, 42);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (6, 14);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (6, 44);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (6, 45);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (6, 36);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (7, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (7, 20);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (7, 21);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (7, 26);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (7, 27);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (8, 29);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (8, 12);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (9, 10);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (10, 11);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (10, 12);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (10, 16);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (11, 30);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (11, 35);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (11, 45);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (12, 19);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (12, 17);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (13, 9);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (13, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (15, 19);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (15, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (15, 30);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (19, 41);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (20, 22);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (20, 1);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (22, 3);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (22, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (23, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (26, 9);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (30, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (30, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (30, 21);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (35, 33);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (35, 8);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (39, 48);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (41, 36);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (41, 37);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (41, 3);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (41, 5);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (44, 10);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (44, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (44, 3);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (45, 12);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (45, 50);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (47, 1);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (47, 2);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (47, 10);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (49, 36);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (49, 6);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (49, 7);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (49, 10);
INSERT INTO `mydb`.`amizade` (`Usuario_id`, `Usuario_id1`) VALUES (49, 15);


